/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'productName' : IDL.Text,
  'timestamp' : IDL.Int,
  'txType' : IDL.Text,
  'customerId' : IDL.Nat,
  'amount' : IDL.Float64,
  'itemsJson' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobile' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'barcode' : IDL.Text,
  'price' : IDL.Float64,
});
export const CustomerBalance = IDL.Record({
  'customer' : Customer,
  'lastPaymentDate' : IDL.Int,
  'totalPaid' : IDL.Float64,
  'totalUdhaar' : IDL.Float64,
  'remainingBalance' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addBatchTransaction' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Opt(Transaction)],
      [],
    ),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Customer)], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Opt(Product)],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Opt(Transaction)],
      [],
    ),
  'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [IDL.Nat, IDL.Nat], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerBalance)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCustomerBalanceSummary' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CustomerBalance)],
      ['query'],
    ),
  'getCustomersSortedByBalance' : IDL.Func(
      [],
      [IDL.Vec(CustomerBalance)],
      ['query'],
    ),
  'getHighBalanceCustomers' : IDL.Func(
      [IDL.Float64],
      [IDL.Vec(CustomerBalance)],
      ['query'],
    ),
  'getInactiveCustomers' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(CustomerBalance)],
      ['query'],
    ),
  'getTransactionsForCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCustomer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'productName' : IDL.Text,
    'timestamp' : IDL.Int,
    'txType' : IDL.Text,
    'customerId' : IDL.Nat,
    'amount' : IDL.Float64,
    'itemsJson' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobile' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'barcode' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CustomerBalance = IDL.Record({
    'customer' : Customer,
    'lastPaymentDate' : IDL.Int,
    'totalPaid' : IDL.Float64,
    'totalUdhaar' : IDL.Float64,
    'remainingBalance' : IDL.Float64,
  });
  
  return IDL.Service({
    'addBatchTransaction' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Opt(Transaction)],
        [],
      ),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Customer)], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Opt(Product)],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Opt(Transaction)],
        [],
      ),
    'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [IDL.Nat, IDL.Nat], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerBalance)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCustomerBalanceSummary' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CustomerBalance)],
        ['query'],
      ),
    'getCustomersSortedByBalance' : IDL.Func(
        [],
        [IDL.Vec(CustomerBalance)],
        ['query'],
      ),
    'getHighBalanceCustomers' : IDL.Func(
        [IDL.Float64],
        [IDL.Vec(CustomerBalance)],
        ['query'],
      ),
    'getInactiveCustomers' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(CustomerBalance)],
        ['query'],
      ),
    'getTransactionsForCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'searchCustomers' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCustomer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };