/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'mobile' : string,
}
export interface CustomerBalance {
  'customer' : Customer,
  'lastPaymentDate' : bigint,
  'totalPaid' : number,
  'totalUdhaar' : number,
  'remainingBalance' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'barcode' : string,
  'price' : number,
}
export interface Transaction {
  'id' : bigint,
  'note' : string,
  'productName' : string,
  'timestamp' : bigint,
  'txType' : string,
  'customerId' : bigint,
  'amount' : number,
  'itemsJson' : [] | [string],
}
export interface _SERVICE {
  'addBatchTransaction' : ActorMethod<
    [bigint, number, string, string],
    [] | [Transaction]
  >,
  'addCustomer' : ActorMethod<[string, string], [] | [Customer]>,
  'addProduct' : ActorMethod<[string, number, string], [] | [Product]>,
  'addTransaction' : ActorMethod<
    [bigint, string, string, number, string],
    [] | [Transaction]
  >,
  'bulkImportProducts' : ActorMethod<[Array<Product>], [bigint, bigint]>,
  'deleteCustomer' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteTransaction' : ActorMethod<[bigint], boolean>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerBalance>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCustomerBalanceSummary' : ActorMethod<[bigint], [] | [CustomerBalance]>,
  'getCustomersSortedByBalance' : ActorMethod<[], Array<CustomerBalance>>,
  'getHighBalanceCustomers' : ActorMethod<[number], Array<CustomerBalance>>,
  'getInactiveCustomers' : ActorMethod<[bigint], Array<CustomerBalance>>,
  'getTransactionsForCustomer' : ActorMethod<[bigint], Array<Transaction>>,
  'searchCustomers' : ActorMethod<[string], Array<Customer>>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateCustomer' : ActorMethod<[bigint, string, string], boolean>,
  'updateProduct' : ActorMethod<[bigint, string, number, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];