/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerBalance {
    customer: Customer;
    lastPaymentDate: bigint;
    totalPaid: number;
    totalUdhaar: number;
    remainingBalance: number;
}
export interface Customer {
    id: bigint;
    name: string;
    createdAt: bigint;
    mobile: string;
}
export interface Product {
    id: bigint;
    name: string;
    createdAt: bigint;
    barcode: string;
    price: number;
}
export interface Transaction {
    id: bigint;
    note: string;
    productName: string;
    timestamp: bigint;
    txType: string;
    customerId: bigint;
    amount: number;
    itemsJson?: string;
}
export interface backendInterface {
    addBatchTransaction(customerId: bigint, totalAmount: number, itemsJson: string, note: string): Promise<Transaction | null>;
    addCustomer(name: string, mobile: string): Promise<Customer | null>;
    addProduct(name: string, price: number, barcode: string): Promise<Product | null>;
    addTransaction(customerId: bigint, productName: string, note: string, amount: number, txType: string): Promise<Transaction | null>;
    bulkImportProducts(productList: Array<Product>): Promise<[bigint, bigint]>;
    deleteCustomer(id: bigint): Promise<boolean>;
    deleteProduct(id: bigint): Promise<boolean>;
    deleteTransaction(id: bigint): Promise<boolean>;
    getAllCustomers(): Promise<Array<CustomerBalance>>;
    getAllProducts(): Promise<Array<Product>>;
    getCustomerBalanceSummary(customerId: bigint): Promise<CustomerBalance | null>;
    getCustomersSortedByBalance(): Promise<Array<CustomerBalance>>;
    getHighBalanceCustomers(threshold: number): Promise<Array<CustomerBalance>>;
    getInactiveCustomers(days: bigint): Promise<Array<CustomerBalance>>;
    getTransactionsForCustomer(customerId: bigint): Promise<Array<Transaction>>;
    searchCustomers(term: string): Promise<Array<Customer>>;
    searchProducts(term: string): Promise<Array<Product>>;
    updateCustomer(id: bigint, name: string, mobile: string): Promise<boolean>;
    updateProduct(id: bigint, name: string, price: number, barcode: string): Promise<boolean>;
}
import type { Customer as _Customer, CustomerBalance as _CustomerBalance, Product as _Product, Transaction as _Transaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBatchTransaction(arg0: bigint, arg1: number, arg2: string, arg3: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatchTransaction(arg0, arg1, arg2, arg3);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatchTransaction(arg0, arg1, arg2, arg3);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCustomer(arg0: string, arg1: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProduct(arg0: string, arg1: number, arg2: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTransaction(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: string): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkImportProducts(arg0: Array<Product>): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportProducts(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportProducts(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async deleteCustomer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<CustomerBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getCustomerBalanceSummary(arg0: bigint): Promise<CustomerBalance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerBalanceSummary(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerBalanceSummary(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomersSortedByBalance(): Promise<Array<CustomerBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomersSortedByBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomersSortedByBalance();
            return result;
        }
    }
    async getHighBalanceCustomers(arg0: number): Promise<Array<CustomerBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighBalanceCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighBalanceCustomers(arg0);
            return result;
        }
    }
    async getInactiveCustomers(arg0: bigint): Promise<Array<CustomerBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveCustomers(arg0);
            return result;
        }
    }
    async getTransactionsForCustomer(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsForCustomer(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsForCustomer(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCustomers(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCustomers(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Transaction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerBalance]): CustomerBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    note: string;
    productName: string;
    timestamp: bigint;
    txType: string;
    customerId: bigint;
    amount: number;
    itemsJson: [] | [string];
}): {
    id: bigint;
    note: string;
    productName: string;
    timestamp: bigint;
    txType: string;
    customerId: bigint;
    amount: number;
    itemsJson?: string;
} {
    return {
        id: value.id,
        note: value.note,
        productName: value.productName,
        timestamp: value.timestamp,
        txType: value.txType,
        customerId: value.customerId,
        amount: value.amount,
        itemsJson: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.itemsJson))
    };
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
